### ISSUE TITLE
replace `publisher` with `xts`

### ISSUE THREAD

**Issue by pr-apes** [speedata/xts#3]
@pgundlach,

I am aware that xts will replace Publisher in the long run.

But I think it would make sense in the meantime to set configuration file and jobname defaults to `xts`.

At least, jobname default value allows output comparison without too much hassle.

Many thanks for your help.

**Comment by pgundlach** [comment]
good point, will do so

**Comment by pgundlach** [comment]
Fixed in release v0.0.4 and commit 4dc8f5620b7db90400d75222909431dd1878c4eb
