### ISSUE TITLE
add mono typeface?

### ISSUE THREAD

**Issue by pr-apes** [speedata/xts#4]
@pgundlach,

this is really a question, since if this request only fits my needs, it might not be required.

I wonder whether it would make sense to add a mono typeface, such as Camingo Code (in Publisher).

It helps to add code snippets and urls (at least, in my case).

Many thanks for your help.

**Comment by pgundlach** [comment]
This makes sense at least as soon HTML support is included. 

Mono fonts will be part of the next release.
