### ISSUE TITLE
option to delay execution `<SetVariable>`

### ISSUE THREAD

**Issue by pr-apes** [speedata/xts#5]
@pgundlach,

in some cases, being able to delay the execution of `<SetVariable>` is very important.

I think that having an attribute (and value) such as `execute="later"` may be very handy.

Many thanks for your help.

**Comment by pgundlach** [comment]
Not sure if I will keep this in xts. It is unclear what (variables) will be saved for later execution.

I will implement user defined functions with parameters which hopefully can achieve what the execute="later" will do, but in a much cleaner way.

**Comment by pgundlach** [comment]
You can read a bit at https://doc.speedata.de/xts/manual/functions/ - v0.0.6 contains the new Function element
