### ISSUE TITLE
attributes for `<PDFOptions>`

### ISSUE THREAD

**Issue by pr-apes** [speedata/xts#7]
@pgundlach,

considering your kind offer from https://github.com/speedata/xts/issues/2#issuecomment-1514530847, I think it is best to run Publisher code with xts (having speedata/publisher#493 fixed would allow to share the layout).

For that, I mainly need the following attributes in `<PDFOptions>`:

* `duplex`
* `picktraybypdfsize`
* `printscaling`

Of course, nothing prevents you from adding other attributes (such as `displaymode` or `hyperlinksbordercolor`, among other ones), but the previous three ones from the list are mandatory for the tool.

In order to manipulate images, some XPath functions would be needed (but I leave the suggestions in a new issue).

Many thanks for your help.

**Comment by pgundlach** [comment]
Will be in the next release

**Comment by pgundlach** [comment]
Implemented in d34ad433ccb99a24ec5174f7c7ecb8bb77a3aebd

**Comment by pgundlach** [comment]
BTW: These features are available in v0.0.5 to be released in a few minutes
