### ISSUE TITLE
XPath `current-page` and `page-number`

### ISSUE THREAD

**Issue by pr-apes** [speedata/xts#8]
@pgundlach,

sorry, but from https://doc.speedata.de/xts/manual/xpath/#layout-functions, the difference between `current-page()` and `page-number()` is not obvious.

My guess is that the first function returns the real page number and the second function might return the page label.

If https://doc.speedata.de/xts/manual/xpath/#layout-functions should include a namespace, it is wiser to type them in full form (`sd:current-page()` instead of `current-page`).

BTW, is there a public repo for the documentation source?

Many thanks for your help.

**Comment by pgundlach** [comment]
> BTW, is there a public repo for the documentation source?

no, not yet. There are proprietary fonts used in the documentation. I'll remove them and create a repository. The documentation is based on [mkdocs](https://www.mkdocs.org) with [material](https://squidfunk.github.io/mkdocs-material/).

**Comment by pgundlach** [comment]
For the documentation: see https://github.com/speedata/xts-doc/discussions/1

**Comment by pgundlach** [comment]
I have updated the manual. Also see https://doc.speedata.de/publisher/en/cookbook/directories-marker/ which will eventually be included into the xts manual.
