### ISSUE TITLE
`visiblebox` for `<Image>`

### ISSUE THREAD

**Issue by pr-apes** [speedata/xts#9]
@pgundlach,

`visiblebox` should be implemented as attribute for `<Image>`.

It would be great that it would default (as in all PDF handling) to media box.

If this is not possible (or you simply prefer to stick to crop box, as in Publisher), media box values should be preferred when these are exceeded by values from the crop box.

We already discussed that (speedata/publisher#468). As tricky as it might seem, crop box values larger than the ones for the media box are valid.

In that case, the spec specifically states that the former should be ignored in favor of the latter (https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#page=636).

Many thanks for your help.

**Comment by pgundlach** [comment]
I am not sure if the MediaBox should be the default box for all the layout functions and for the image inclusion. CropBox is what the user should see in the PDF when included and not the media box?! If this is true, I think it makes sense to have the crop box as a default for the other functions.

**Comment by pgundlach** [comment]
Next version of XTS implements that the boxes should not be larger than the mediabox.

**Comment by pgundlach** [comment]
Release will be uploaded as soon as possible
